#Hugo configuration
title = "Test IMA"
baseURL = "https:\/\/www.imatest.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
